wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1650723578
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      4: 3.8.10
      5: 0.12.15
      6: 4.17.0
      8:
      - 5
